### ISSUE TITLE
pnpm workspaces support

### ISSUE THREAD

**Issue by juanpicado** [eBayClassifiedsGroup/update-ts-references#10]
Hi :upside_down_face: 

I like this tool and I plan to use it at Verdaccio, we have an increasing number of modules and update references manually is though, but we uses `pnpm` and this requires some sort of refactoring to your tooling.  Would you be interested?

https://pnpm.js.org/en/pnpm-workspace_yaml
https://github.com/verdaccio/verdaccio/blob/5.x/pnpm-workspace.yaml

It might be required to add some extra deps, as yaml to js and add some new CLI argument like `--strategy` or `--support` so users can choose and even add support for others tooling. 

I'd like to work on this but first know your thoughts.

**Comment by MKruschke** [comment]
Hey Juan,
hehe I actually was thinking about that as well after checking your repo 😄.

To add some new dependency to read yaml files would be ok and I think we can autodetect pnpm by searching for the pnpm workspace file or? If yes we don't need an extra cli input. 

Interesting tho is that you can add exclude pattern there as well. 

Additionally I was also thinking about the [referencing-workspace-packages-through-relative-path](https://pnpm.js.org/en/workspaces#referencing-workspace-packages-through-relative-path) . It is also used by [yarn2](https://yarnpkg.com/features/workspaces#workspace-ranges-workspace) I don't know yet how flexible that path linking is, but we can start without considering it.

**Comment by juanpicado** [comment]
Let me dive into pnpm packages and see whether they have some we can use easily.

**Comment by gbouteiller** [comment]
Hello guys, any news about that feature?

**Comment by juanpicado** [comment]
> Hello guys, any news about that feature?

No from my side, I am still willing to do it but when I have some extra time.

**Comment by MKruschke** [comment]
Hey Juan,
I thought on spending some time for general improvements. If it is fine for you I will just grab this one as my first task.

**Comment by MKruschke** [comment]
@gbouteiller Just released the new version [2.1.1](https://github.com/eBayClassifiedsGroup/update-ts-references/releases/tag/2.1.1). If you rely on pnpm aliases and this needs to supported as well, please let us know via the issue #13
