### ISSUE TITLE
Automate publish version to npmjs

### ISSUE THREAD

**Issue by juanpicado** [eBayClassifiedsGroup/update-ts-references#20]
This is a healthy feature to have, but I wonder which strategy would be the best one. Thoughts on this ?

I would like to bring this to a PR.

**Comment by MKruschke** [comment]
Didn't think about that so far. What would your proposal here?

**Comment by juanpicado** [comment]
> Didn't think about that so far. What would your proposal be here?

sorry my friend I missed this.

Well, I guess people will contribute more often and you might need to delegate a machine to do that job.  There are a lot of possibilities for how to automate this or semi-automate, I can elaborate a bit more with proposals if you like the idea.
