### ISSUE TITLE
Accommodate repos without root tsconfig.json files

### ISSUE THREAD

**Issue by benkeen** [eBayClassifiedsGroup/update-ts-references#43]
Hi! Great script.

In our Rush-based monorepo we don't have a root tsconfig file. The command works okay, but throws an error when it can't find the root file. I tried omitting `rootConfigName` in our yaml file, but then it just defaults to `tsconfig.json`. 

Just a heads up - thanks!

**Comment by MKruschke** [comment]
@benkeen you can now use the option withoutRootConfig for your repos

**Comment by benkeen** [comment]
Thanks @MKruschke!
