### ISSUE TITLE
keep removing reference from 2nd project

### ISSUE THREAD

**Issue by ravi005e** [eBayClassifiedsGroup/update-ts-references#7]
here is a snippet from the main package.json

  "private": true,
  "workspaces": [
    "nightwatch-core",
    "sample-core",
    "sample-test"
  ],
  "engines": {
    "node": ">=10.0.x"
  },

removes references object after doing yarn install

>yarn install
yarn install v1.22.5
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.2.1: The platform "win32" is incompatible with this module.
info "fsevents@2.2.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
$ update-ts-references
updating tsconfigs
Done in 2.68s.

  "references": [
    {
      "path": "..\\nightwatch-core"
    }
  ]

it shouldn't be removed

**Comment by MKruschke** [comment]
Hi @ravi005e,
thanks for adding that issue, but can you provide a better example about your project setup? Something similar to one of the folders in https://github.com/eBayClassifiedsGroup/update-ts-references/tree/master/tests/scenarios would be nice.

With the given information I don't know which tsconfig is affected or if you maybe missed to have nightwatch-core referenced in the dependencies.

Best Mirko

**Comment by MKruschke** [comment]
Hey @ravi005e,
seems that your are busy and couldn't provide an example. Let me try to explain the tool a little bit: 

In general this tool will automatically update the references and can not retain previous manual added paths. If you would like to have nightwatch-core as reference you need to specific it as dependency in your packages json of your second project/package. The only exception here is when we talk about the tsconfig in the root of the workspace these are added on the fact that packages providing their own tsconfig.json.

I hope this explanation will help you and will close that issue for now.
