### ISSUE TITLE
Improve cross OS setups

### ISSUE THREAD

**Issue by Flarna** [eBayClassifiedsGroup/update-ts-references#9]
I work in a project where some people use windows and others use linux.

node, typescript (and most other tools) work fine if unix style paths are used in e.g. tsconfig.json

This tool is currently modifying all our tsconfig.json files if executed on windows by replacing all / by \\.

I think this could be easily fixed by adding `.replace(/\\/g, '/')` to the `path.relative()` results.

**Comment by MKruschke** [comment]
Hi @Flarna,
thank you for your input here, especially because we using this internally on unix systems only I wasn't aware of that.

PR #11 will address that issue and after that is merged and published it would be could awesome if you can double check it on your side.

Best Mirko

**Comment by MKruschke** [comment]
@Flarna v2.0.0 is published. Wish you also wonderful x-mas 🎄
